// src/components/nfse/styles.ts

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
    },
    header: {
        backgroundColor: 'white',
        padding: 24,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    stepsContainer: {
        backgroundColor: 'white',
        margin: 16,
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    stepsTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 16,
    },
    stepItem: {
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    stepHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    stepIcon: {
        fontSize: 24,
        marginRight: 12,
        marginTop: 2,
    },
    stepContent: {
        flex: 1,
    },
    stepTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 4,
    },
    stepDescription: {
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },
    stepAction: {
        backgroundColor: '#6200ee',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignSelf: 'flex-start',
        marginTop: 8,
        marginLeft: 36,
    },
    stepActionText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
    card: {
        backgroundColor: 'white',
        margin: 16,
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    cardDescription: {
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
        marginBottom: 20,
    },
    successContainer: {
        backgroundColor: '#e8f5e8',
        borderColor: '#4CAF50',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
    },
    successTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2e7d32',
        marginBottom: 8,
    },
    successText: {
        fontSize: 14,
        color: '#2e7d32',
        marginBottom: 4,
    },
    errorContainer: {
        backgroundColor: '#ffebee',
        borderColor: '#f44336',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
    },
    errorText: {
        color: '#d32f2f',
        fontSize: 14,
        lineHeight: 20,
    },
    infoBox: {
        backgroundColor: '#e3f2fd',
        borderColor: '#2196f3',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
    },
    infoText: {
        color: '#1565c0',
        fontSize: 14,
        lineHeight: 20,
        marginTop: 8
    },
    label: {
        fontSize: 14,
        fontWeight: '500',
        marginBottom: 8,
        marginTop: 16,
        color: '#333',
    },
    picker: {
        backgroundColor: '#f8f9fa',
        marginBottom: 16,
    },
    input: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 6,
        marginBottom: 16,
    },
    inputText: {
        fontSize: 14,
        color: '#333',
    },
    helperText: {
        fontSize: 12,
        color: '#666',
        marginBottom: 8,
        lineHeight: 16,
        fontStyle: 'italic',
    },
    textArea: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 6,
        marginBottom: 16,
        minHeight: 120,
        textAlignVertical: 'top',
        fontSize: 14,
        color: '#333',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    primaryButton: {
        backgroundColor: '#6200ee',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 8,
    },
    secondaryButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#6200ee',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 8,
    },
    button: {
        backgroundColor: '#6200ee',
        padding: 12,
        borderRadius: 4,
        alignItems: 'center',
        marginTop: 8,
    },
    buttonDisabled: {
        backgroundColor: '#ccc',
        borderColor: '#ccc',
    },
    primaryButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
    },
    secondaryButtonText: {
        color: '#6200ee',
        fontSize: 16,
        fontWeight: '500',
    },
    navigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
    },
    navButton: {
        backgroundColor: '#6c757d',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    navButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },

    // Testing screen specific styles
    sectionTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        color: '#333',
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    statusIndicator: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
    },
    statusText: {
        fontSize: 14,
        color: '#333',
    },
    certificateInfo: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 4,
        marginBottom: 12,
    },
    testResult: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 4,
        marginTop: 12,
    },
    resultTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    resultText: {
        fontSize: 12,
        color: '#666',
        marginBottom: 4,
    },
    safetyBox: {
        backgroundColor: '#f0f9ff',
        borderColor: '#0ea5e9',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
    },
    safetyTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#0284c7',
        marginBottom: 8,
    },
    safetyText: {
        fontSize: 13,
        color: '#0369a1',
        marginBottom: 4,
        lineHeight: 18,
    },
    warningContainer: {
        backgroundColor: '#fff3cd',
        borderColor: '#ffc107',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        marginTop: 12,
    },
    warningText: {
        color: '#856404',
        fontSize: 13,
        lineHeight: 18,
        marginBottom: 4,
    },
    backButton: {
        backgroundColor: '#28a745',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    backButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
    successButton: {
        backgroundColor: '#4CAF50',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    successButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
});